# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dmat_pb2 as dmat__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dmat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZygoStub(object):
    """-------------------------------------------------------------------------- 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Expose = channel.unary_unary(
                '/dmat.Zygo/Expose',
                request_serializer=dmat__pb2.ExposeRequest.SerializeToString,
                response_deserializer=dmat__pb2.ExposeReply.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/dmat.Zygo/Retrieve',
                request_serializer=dmat__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=dmat__pb2.RetrieveReply.FromString,
                _registered_method=True)


class ZygoServicer(object):
    """-------------------------------------------------------------------------- 
    """

    def Expose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZygoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Expose': grpc.unary_unary_rpc_method_handler(
                    servicer.Expose,
                    request_deserializer=dmat__pb2.ExposeRequest.FromString,
                    response_serializer=dmat__pb2.ExposeReply.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=dmat__pb2.RetrieveRequest.FromString,
                    response_serializer=dmat__pb2.RetrieveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dmat.Zygo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dmat.Zygo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Zygo(object):
    """-------------------------------------------------------------------------- 
    """

    @staticmethod
    def Expose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dmat.Zygo/Expose',
            dmat__pb2.ExposeRequest.SerializeToString,
            dmat__pb2.ExposeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dmat.Zygo/Retrieve',
            dmat__pb2.RetrieveRequest.SerializeToString,
            dmat__pb2.RetrieveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
