# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dmat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dmat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndmat.proto\x12\x04\x64mat\"\x0f\n\rExposeRequest\"\x1e\n\x0b\x45xposeReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x11\n\x0fRetrieveRequest\"1\n\rRetrieveReply\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x10\n\x08\x66iledata\x18\x02 \x01(\x0c\x32t\n\x04Zygo\x12\x32\n\x06\x45xpose\x12\x13.dmat.ExposeRequest\x1a\x11.dmat.ExposeReply\"\x00\x12\x38\n\x08Retrieve\x12\x15.dmat.RetrieveRequest\x1a\x13.dmat.RetrieveReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dmat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPOSEREQUEST']._serialized_start=20
  _globals['_EXPOSEREQUEST']._serialized_end=35
  _globals['_EXPOSEREPLY']._serialized_start=37
  _globals['_EXPOSEREPLY']._serialized_end=67
  _globals['_RETRIEVEREQUEST']._serialized_start=69
  _globals['_RETRIEVEREQUEST']._serialized_end=86
  _globals['_RETRIEVEREPLY']._serialized_start=88
  _globals['_RETRIEVEREPLY']._serialized_end=137
  _globals['_ZYGO']._serialized_start=139
  _globals['_ZYGO']._serialized_end=255
# @@protoc_insertion_point(module_scope)
